# Imagen base oficial de Python 3.11
FROM python:3.11-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de dependencias
COPY src/api/ api/.

# Instala git y las dependencias
RUN apt-get update \
    && pip install -r api/requirements.txt 

# Expone el puerto en el que correrá la API (FastAPI por defecto en 8000)
EXPOSE 8000

# Comando para ejecutar la API
CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8000"]
