"""Centralized component ids."""


class IDS:
    MODEL_REFRESH_BUTTON = "model-refresh-button"
    MODEL_SELECTOR = "model-selector"
    MODEL_INFO = "model-info"

    GLOBAL_DEPENDENCE_FEATURE = "global-dependence-feature"
    GLOBAL_SUMMARY_GRAPH = "global-summary-graph"
    GLOBAL_BAR_GRAPH = "global-bar-graph"
    GLOBAL_DEPENDENCE_GRAPH = "global-dependence-graph"
    GLOBAL_INTERACTION_GRAPH = "global-interaction-graph"
    GLOBAL_NOTE = "global-note"
    GLOBAL_EQUIVALENT_DEPTH_TABS = "global-equivalent-depth-tabs"
    GLOBAL_EQUIVALENT_ZOOM = "global-equivalent-zoom"
    GLOBAL_EQUIVALENT_CONTENT = "global-equivalent-content"
    GLOBAL_EQUIVALENT_TREE_IMAGE = "global-equivalent-tree-image"

    BEHAVIOUR_ANCHOR_INDEX = "behaviour-anchor-index"
    BEHAVIOUR_ICE_FEATURE = "behaviour-ice-feature"
    SURFACE_HEATMAP = "surface-heatmap"
    SMILE_GRAPH = "smile-graph"
    TERM_GRAPH = "term-graph"
    ICE_GRAPH = "ice-graph"
    ALE_GRAPH = "ale-graph"
    LOCAL_SURFACE_GRAPH = "local-surface-graph"
    BEHAVIOUR_WARNINGS = "behaviour-warnings"

    SAMPLE_MODE = "sample-mode"
    SAMPLE_INDEX = "sample-index"
    SAMPLE_INDEX_CONTAINER = "sample-index-container"
    SAMPLE_MANUAL_FORM = "sample-manual-form"
    SAMPLE_RUN_BUTTON = "sample-run-button"
    SAMPLE_OUTPUT = "sample-output"
    SAMPLE_WATERFALL = "sample-waterfall"
    SAMPLE_NEIGHBORS = "sample-neighbors"
    SAMPLE_COMPARISON = "sample-comparison"

    DIAGNOSIS_METRICS = "diagnosis-metrics"
    DIAGNOSIS_SCATTER = "diagnosis-scatter"
    DIAGNOSIS_MONEYNESS = "diagnosis-moneyness"
    DIAGNOSIS_MATURITY = "diagnosis-maturity"
    DIAGNOSIS_HEATMAP = "diagnosis-heatmap"
    DIAGNOSIS_WARNINGS = "diagnosis-warnings"
